sudo: required
language: c
services:
  - docker
script:
  - make
  - docker build -t vxlabs/glide:$TRAVIS_COMMIT . ;
after_success:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push vxlabs/glide:$TRAVIS_COMMIT;
  - docker tag vxlabs/glide:$TRAVIS_COMMIT vxlabs/glide:latest
  - docker push vxlabs/glide:latest
